[package]
name = "tic2mqtt"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros", "signal", "io-std"] }
tokio-serial = "5.4.5"
rumqttc = "0.18"
