[package]
name = "tic2mqtt"
version = "0.0.0-ci"
edition = "2024"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true
panic = "abort"

[dependencies]
serialport = "4"
ctrlc = "3"
paho-mqtt = "0.13"
